ALTER TABLE turf_owners ADD COLUMN IF NOT EXISTS location_lat DECIMAL(10, 7);
ALTER TABLE turf_owners ADD COLUMN IF NOT EXISTS location_lng DECIMAL(10, 7);
ALTER TABLE turf_owners ADD COLUMN IF NOT EXISTS location_label TEXT;
ALTER TABLE turf_owners ADD COLUMN IF NOT EXISTS kyc_doc_name VARCHAR(255);
ALTER TABLE turf_owners ADD COLUMN IF NOT EXISTS account_holder VARCHAR(100);
ALTER TABLE turf_owners ADD COLUMN IF NOT EXISTS turf_name VARCHAR(150);
ALTER TABLE turf_owners ADD COLUMN IF NOT EXISTS reject_note TEXT;
ALTER TABLE turf_owners ADD COLUMN IF NOT EXISTS applied_at TIMESTAMPTZ DEFAULT NOW();
